<?php

namespace Container9JXEIOL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9CHdI4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9_CHdI4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9_CHdI4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'employee' => ['privates', '.errored..service_locator.9_CHdI4.App\\Entity\\Employee', NULL, 'Cannot autowire service ".service_locator.9_CHdI4": it references class "App\\Entity\\Employee" but no such service exists.'],
            'employeeRepository' => ['privates', 'App\\Repository\\EmployeeRepository', 'getEmployeeRepositoryService', true],
        ], [
            'employee' => 'App\\Entity\\Employee',
            'employeeRepository' => 'App\\Repository\\EmployeeRepository',
        ]);
    }
}
