<?php

namespace Container9JXEIOL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Eyr3PtwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Eyr3Ptw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Eyr3Ptw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'employee' => ['privates', '.errored..service_locator.Eyr3Ptw.App\\Entity\\Employee', NULL, 'Cannot autowire service ".service_locator.Eyr3Ptw": it references class "App\\Entity\\Employee" but no such service exists.'],
        ], [
            'employee' => 'App\\Entity\\Employee',
        ]);
    }
}
