<?php

namespace Container9JXEIOL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9_CHdI4.App\Entity\Employee' shared service.
     *
     * @return \App\Entity\Employee
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9_CHdI4": it references class "App\\Entity\\Employee" but no such service exists.');
    }
}
